coverage_service: cobertura_xml
xcodeproj: Cardapio USP.xcodeproj
workspace: Cardapio USP.xcworkspace
scheme: Cardapio USP
output_directory: ./metrics/reports
source_directory: Cardapio USP
binary_basename: Cardapio USP

ignore:
  - Pods/*
  - Cardapio USPTests/*
  - "Cardapio USP/AF*"
  - Index/*
  - "*.framework/*"
  - Crashlytics.framework/*
  - Fabric.framework/*
